# -*- coding: utf-8 -*-
"""JogoForca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18XYh0gRn1H7wBk2YjtwOj0-14olqXcL1
"""

import random
import collections
def split(word): 
    return list(word) 
print("Jogo da Forca dos meses\nVocê tem 5 tentativas")

palavras = ["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"]
sorteada = random.choice(palavras)
separada = split(sorteada)
print('A palavra sorteada tem %d letras\n'%(len(separada)))
tent = 5
lista = []
listaE = []
while tent > 0:
            a = str(input("\ndetermine uma letra: "))
            if (a in lista):
                 print('Essa letra já foi')
            elif (a in separada): 
               print ('\nA letra "%s" pertence a palavra sorteada!\n\nescolha outra letra agora' %(a)) 
               lista.append(a)
               print('Letras já acertadas')
               print(lista)
               if collections.Counter(lista) == collections.Counter(separada):
                 print('\n\n\nVoce ganhou! A palavra era %s'%(sorteada))
                 break
            elif (a in lista):
                 print('Essa letra já foi')
            elif (a in listaE):
                 print('\nVoce já errou essa letra')
            else:
               print("\nNão existe, menos uma tentativa")
               listaE.append(a)
               tent -= 1
if tent == 0:
         print('Voce perdeu!')